import tkinter as tk
from tkinter import ttk, messagebox
import subprocess
import webbrowser

# Sample locations and categories
locations = ["GEU", "Clock Tower", "ISBT", "Rajpur Road", "Paltan Bazaar"]
categories = ["hospital", "bus stop", "police station"]

def run_route_optimizer():
    source = source_combo.get()
    dest = dest_combo.get()
    cat = category_combo.get()

    if not source or not dest or not cat:
        messagebox.showerror("Input Error", "Please select source, destination, and category.")
        return

    # Call your compiled C executable
    result = subprocess.run(
        ['route_optimizer.exe'],  # Make sure this matches your compiled C file name
        input=f"{source}\n{dest}\n{cat}\n",
        text=True,
        capture_output=True
    )

    # Show output in the text box
    output_text.delete(1.0, tk.END)
    output_text.insert(tk.END, result.stdout)

    # Open the route map (output generated by Python/Folium)
    webbrowser.open("route_output.html")

# Create GUI
root = tk.Tk()
root.title("Route Optimization System")

# Source selection
tk.Label(root, text="Source:").grid(row=0, column=0, padx=10, pady=10)
source_combo = ttk.Combobox(root, values=locations, state="readonly")
source_combo.grid(row=0, column=1)

# Destination selection
tk.Label(root, text="Destination:").grid(row=1, column=0, padx=10, pady=10)
dest_combo = ttk.Combobox(root, values=locations, state="readonly")
dest_combo.grid(row=1, column=1)

# Category selection
tk.Label(root, text="Category:").grid(row=2, column=0, padx=10, pady=10)
category_combo = ttk.Combobox(root, values=categories, state="readonly")
category_combo.grid(row=2, column=1)

# Action button
tk.Button(root, text="Find Route", command=run_route_optimizer).grid(row=3, column=0, columnspan=2, pady=20)

# Output box
output_text = tk.Text(root, height=10, width=50)
output_text.grid(row=4, column=0, columnspan=2, padx=10, pady=10)

root.mainloop()
